server:
  port: ${SERVER_PORT:5000}

spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: wowbraq@gmail.com
    password: ${SPRING_MAIL_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: ${SPRING_MULTIPART_MAX_FILE_SIZE:512MB}
      max-request-size: ${SPRING_MULTIPART_MAX_REQUEST_SIZE:512MB}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
  jpa:
    open-in-view: ${SPRING_JPA_OPEN_IN_VIEW:false}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQL8Dialect}

jwt:
  secret: ${JWT_SECRET}
  expirationMinutes: ${JWT_EXPIRATIONMINUTES:120}

management:
  endpoints:
    web:
      exposure:
        include: health,info

storage:
  provider: s3

aws:
  region: ${AWS_REGION}
  s3:
    bucket: ${BUCKET}
    public-base-url: ${AWS_S3_PUBLIC_BASE_URL}

CORS_ALLOWED_ORIGINS: {$CORS_ALLOWED_ORIGINS}

